// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAueR5V-hH9I0nOrDLqYPEbxP7qmvfnIi8',
    appId: '1:744467284289:web:0397e41591c64ca02ea1c0',
    messagingSenderId: '744467284289',
    projectId: 'fir-services-2e289',
    authDomain: 'fir-services-2e289.firebaseapp.com',
    databaseURL: 'https://fir-services-2e289-default-rtdb.firebaseio.com',
    storageBucket: 'fir-services-2e289.appspot.com',
    measurementId: 'G-JJS4WGSF3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxSZ7DC-o1pAzS09GWX7vIGjnT4Kd34M',
    appId: '1:744467284289:android:eeea35ccda869b382ea1c0',
    messagingSenderId: '744467284289',
    projectId: 'fir-services-2e289',
    databaseURL: 'https://fir-services-2e289-default-rtdb.firebaseio.com',
    storageBucket: 'fir-services-2e289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZeJZtkJbXGQHEWjEx0XwT05uuIySi00',
    appId: '1:744467284289:ios:f387d3624afeddee2ea1c0',
    messagingSenderId: '744467284289',
    projectId: 'fir-services-2e289',
    databaseURL: 'https://fir-services-2e289-default-rtdb.firebaseio.com',
    storageBucket: 'fir-services-2e289.appspot.com',
    iosBundleId: 'com.example.firebaseServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZeJZtkJbXGQHEWjEx0XwT05uuIySi00',
    appId: '1:744467284289:ios:d302cdd957f9ca642ea1c0',
    messagingSenderId: '744467284289',
    projectId: 'fir-services-2e289',
    databaseURL: 'https://fir-services-2e289-default-rtdb.firebaseio.com',
    storageBucket: 'fir-services-2e289.appspot.com',
    iosBundleId: 'com.example.firebaseServices.RunnerTests',
  );
}
